Использование NumPy

Описание работы

Данная работа представлена набором заданий, которые позволят на практике узнать о возможностях библиотеки Numerical Python.

1. Выполнить установку и подключение библиотеки в программе на языке Python. Для этого рекомендуется использовать менеджер пакетов pip.

In [ ]:
import numpy as np
import random
from numpy import linalg, random
import time

2. Выполнить генерацию:



a. линейного массива (вектора) чисел с плавающей точкой произвольного размера;

In [ ]:
arr = np.full((10, 10), 0)

In [ ]:
arr

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])


b. выполнить генерацию двумерного массива (матрицы) чисел с плавающей точкой произвольного размера;

In [ ]:
arr_2 = np.linspace(1, 3, 6)
random.shuffle(arr_2)

In [ ]:
arr_2.reshape(2,3)

array([[3. , 2.6, 1.4],
       [2.2, 1. , 1.8]])

c. генерацию массивов выполнять с размерностью в сотни, тысячи, сотни тысяч элементов.

d. для каждого массива выполнить оценку времени, затраченного на генерацию.

e. сравнить показатели с массивами, генерируемыми средствами стандартной библиотеки языка Python аналогичной размерности.

In [ ]:
arr_3 = np.arange(0,2)

In [ ]:
arr_3

array([0, 1])

In [ ]:
arr_3 = np.random.randint(1, 100, 100)
%time


CPU times: user 4 µs, sys: 1 µs, total: 5 µs
Wall time: 8.82 µs


In [ ]:
arr_3 = np.random.randint(1, 100, 1000)
%time

CPU times: user 4 µs, sys: 0 ns, total: 4 µs
Wall time: 9.54 µs


In [ ]:
arr_3 = np.random.randint(1, 100, 100000)
%time


CPU times: user 4 µs, sys: 1 µs, total: 5 µs
Wall time: 8.82 µs


In [ ]:
items = list(range(100))
%time

CPU times: user 4 µs, sys: 1 µs, total: 5 µs
Wall time: 8.82 µs


In [ ]:
items = list(range(1000))
%time

CPU times: user 4 µs, sys: 1 µs, total: 5 µs
Wall time: 8.82 µs


In [ ]:
items = list(range(100000))
%time

CPU times: user 4 µs, sys: 1e+03 ns, total: 5 µs
Wall time: 8.11 µs


3. Выполнить все арифметические операции над элементами двумерного массива.

In [ ]:
x = np.random.randint(5, 50, (5, 3))
y = np.random.randint(55, 170, (5, 3))

In [ ]:
x_y = x*y
x_y

array([[2822,  405,  630],
       [1728, 2054,  994],
       [4958, 3080, 6952],
       [1065,  740, 1728],
       [1254, 2378,  972]])

In [ ]:
x_y = x+y
x_y

array([[183,  86,  79],
       [156, 105, 149],
       [171, 123, 202],
       [ 86,  84, 114],
       [ 79, 111,  93]])

In [ ]:
x_y = x-y
x_y

array([[-149,  -76,  -61],
       [-132,  -53, -135],
       [ -97,  -53, -114],
       [ -56,  -64,  -78],
       [ -35,  -53,  -69]])

In [ ]:
x_t = np.transpose(x)
print(x)
print("")
print(x_t)

[[17  5  9]
 [12 26  7]
 [37 35 44]
 [15 10 18]
 [22 29 12]]

[[17 12 37 15 22]
 [ 5 26 35 10 29]
 [ 9  7 44 18 12]]


4. В качестве полноценного упражнения реализовать игру «Жизнь» использованием NumPy.

In [ ]:
def neighbor_xy(x, y):
    for dx, dy in {
        (0, 1),
        (1, 1),
        (1, 0),
        (1, -1),
        (0, -1),
        (-1, -1),
        (-1, 0),
        (-1, 1)
    }:
        yield x + dx, y + dy

def show_field(field):
    for y in range(MAX_SIZE):
        print(f'{field[y]}')
        
def get_empty_field():    
    return np.full((MAX_SIZE, MAX_SIZE), DEAD)
        
def is_live(field, neighbor_x, neighbor_y):
    return 0 <= neighbor_x < MAX_SIZE and 0 <= neighbor_y < MAX_SIZE and field[neighbor_y][neighbor_x] == LIVE

In [ ]:
MAX_SIZE = 20
DEAD = 0
LIVE = 1
field = np.random.randint(0,2,(MAX_SIZE,MAX_SIZE))

while True:
    show_field(field)
    buffer = get_empty_field()
    for y in range(MAX_SIZE):
        for x in range(MAX_SIZE):
            c = field[y][x]
            neighbors = 0
            for neighbor_x, neighbor_y in neighbor_xy(x, y):
                neighbors += 1 if is_live(field, neighbor_x, neighbor_y) else 0
                pass
            if c == DEAD:
                buffer[y][x] = LIVE if neighbors == 3 else DEAD
            else:
                buffer[y][x] = LIVE if neighbors == (2, 3) else DEAD
                
    if (field == buffer).all():
        print('stasis')
        break
    field = buffer
    time.sleep(2)
    print('Next: ')

[0 0 1 0 0 0 1 1 0 0 1 0 1 0 0 0 0 1 0 0]
[1 1 0 0 1 0 1 0 0 1 0 1 0 1 1 0 0 0 0 1]
[0 1 1 0 1 0 0 0 0 0 0 1 0 0 0 0 1 0 1 1]
[1 1 1 0 0 1 1 1 1 0 1 0 1 0 1 1 0 0 0 1]
[1 0 0 0 0 0 1 1 0 1 0 1 0 0 1 1 0 0 1 0]
[0 0 1 0 0 1 1 0 1 1 0 1 1 0 0 0 1 1 1 1]
[0 1 1 0 0 0 1 0 0 1 0 0 1 1 0 0 1 0 1 1]
[0 1 0 1 0 1 0 1 1 1 0 1 1 1 0 1 1 1 1 1]
[1 1 0 0 1 0 1 0 1 1 0 0 0 0 0 0 0 0 0 0]
[0 1 0 0 1 1 0 1 1 1 1 1 1 0 0 0 1 1 1 0]
[0 1 1 1 0 1 0 1 1 0 1 0 1 0 0 1 0 0 0 0]
[1 1 1 0 0 1 1 0 1 0 0 1 0 0 0 0 0 0 1 1]
[0 1 0 1 1 0 0 1 0 1 0 0 1 0 1 0 1 1 1 1]
[1 1 0 1 0 1 0 0 1 0 0 1 1 0 1 1 0 0 1 1]
[0 1 1 1 0 1 1 0 1 0 1 0 1 0 0 0 0 1 0 1]
[1 0 0 1 1 1 1 1 0 1 0 0 0 0 0 1 0 1 1 0]
[0 1 1 1 1 0 1 1 1 1 0 1 1 0 0 1 1 1 1 0]
[0 0 0 1 1 1 0 0 1 1 0 1 0 0 0 1 1 0 0 0]
[0 1 0 0 0 1 1 1 0 0 1 0 1 1 1 1 1 0 1 1]
[0 1 0 1 0 1 0 0 0 1 1 1 1 0 0 1 1 1 1 0]
Next: 
[0 1 0 0 0 1 0 0 0 0 0 1 0 1 0 0 0 0 0 0]
[0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0]
[0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0]
[0 0 0 1 0 0 0 0 0 1 0 0 0 